### ISSUE TITLE
Using this in a Typescript codebase

### ISSUE THREAD

**Issue by hennessyevan** [zhangkaiyulw/seedgoose#12]
Is there anyway to easily consume models written in typescript with this module?

Would I have to use this programatically?

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan, the upcoming 2.0 supports this out of the box.

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan can you try 2.0 to see if this problem has been fixed?

**Comment by hennessyevan** [comment]
Wow, that's great news, thanks for this. Unfortunately I'm still getting with v2.0

```bash
(node:10379) UnhandledPromiseRejectionWarning: lib/models/About.ts:1
import mongoose from 'mongoose'
       ^^^^^^^^

SyntaxError: Unexpected identifier
    at Module._compile (internal/modules/cjs/loader.js:703:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Module.require (internal/modules/cjs/loader.js:666:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Array.forEach (<anonymous>)
    at node_modules/seedgoose/lib/index.js:55:23
    at Generator.next (<anonymous>)
    at node_modules/seedgoose/lib/index.js:8:71
```

My `.seedgooserc.js` looks like
```js
module.exports = {
  modelBaseDirectory: 'lib/models',
  models: '*.ts',
  data: 'seeds',
  db: 'mongodb://localhost:27017/test',
}
```

**Comment by hennessyevan** [comment]
I'm thinking an implementation like this one could do well to support a wide swath of pre-compilation https://github.com/tj/node-migrate/blob/master/lib/register-compiler.js

**Comment by zhangkaiyulw** [comment]
The bug is from `modelFileList.forEach(require);`.
I think it can be fixed with this package https://github.com/zhangkaiyulw/load-any-file

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan try 2.0.1

**Comment by hennessyevan** [comment]
So it now loads the files which is great! It seems to be populating every field with an empty `Object` though.

For example my User model looks like

```ts
const userSchema = new Schema(
  {
    email: {
      type: String,
      unique: true,
      required: true,
      validate: [validator.isEmail, 'Invalid Email Address'],
    },
    firstName: {
      required: true,
      type: String,
    },
    lastLogin: Date,
    lastName: {
      required: true,
      type: String,
    },
    password: {
      type: String,
      required: true,
      min: 6,
      max: 40,
      select: false,
    },
    prefix: String,
    username: String,
  },
  {
    timestamps: true,
  }
)

const User: Model<UserModel> = mongoose.model('user', userSchema)
export default User
```

And the data file I'm using for seeding

```json
{
  "Jack": {
    "firstName": "Jack",
    "lastName": "Jill",
    "email": "jack.jill@email.com",
    "username": "jack.jill",
    "password": "asdb723nfd"
  }
}
```

I'll try making a repro for this

**Comment by hennessyevan** [comment]
If you run https://github.com/hennessyevan/seedgoose-repro you'll see that it creates empty objects.

![image](https://user-images.githubusercontent.com/16711653/62634781-76768f80-b904-11e9-940a-3f3a35e88489.png)

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan, I have this bug in my new javaScript project too. I'm looking into it.

**Comment by hennessyevan** [comment]
Thanks @zhangkaiyulw im really intrigued by the concept of seedgoose, great work. Let me know if there’s anything I can do to help

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan, try 2.0.2.
The bug is caused by https://github.com/zhangkaiyulw/seedgoose/commit/c4db44c1a64a62815101f8a16e67a62b3b6fcdc7 which is 'missing await'.

**Comment by hennessyevan** [comment]
Working! Thanks, I'm excited to start using this package. Cheers 🍺
