### ISSUE TITLE
Dynamic References via `refPath` in SubDocuments

### ISSUE THREAD

**Issue by hennessyevan** [zhangkaiyulw/seedgoose#13]
## Request
Mongoose allows us to set dynamic references via `refPath`. Is there any chance of being able to do that with seedgoose? I love this library btw, it has been so nice to use.

## Current Behavior
Right now if I set a dynamic ref there are no errors but seedgoose cannot find the collection to use so instead of replacing the id placeholder it just deletes it.

e.g. (from the [docs](https://mongoosejs.com/docs/populate.html#dynamic-ref))
```js
const schema = new Schema({
  on: {
    type: Schema.Types.ObjectId,
    required: true,
    // Instead of a hardcoded model name in `ref`, `refPath` means Mongoose
    // will look at the `onModel` property to find the right model.
    refPath: 'onModel'
  },
  onModel: {
    type: String,
    required: true,
    enum: ['BlogPost', 'Product']
  }
})
```

Results in 
```js
{
  _id: ObjectId("5d5d87cd977ac93db95a3c49"),
  onModel: 'Product'
}
```

**Comment by hennessyevan** [comment]
Dug into the source code and see that you already have something written for this, I'll take a look at why it's not working on my end.

**Comment by hennessyevan** [comment]
So the issue seems to be with dynamicRefs in nested schemas. I've updated my [repro](https://github.com/hennessyevan/seedgoose-repro) to reflect this simply.

I'll keep digging around to try and figure this out but I suspect it's something to do with the `refPath` check not happening when looping through nested schemas. Seedgoose has no problem with static `refs` in nested schemas nor with `refPath` in flat schemas.

My schema shape for this is similar to:
```js
const articleSchema = new mongoose.Schema({
  article: {
    type: mongoose.Schema.Types.ObjectId,
    refPath: "domain"
  },
  domain: String
});

const userSchema = new mongoose.Schema({
  name: String,
  articles: [articleSchema]
});
```

**Comment by hennessyevan** [comment]
So I spent some time probing around and by the time seedgoose gets to the subdocument on https://github.com/zhangkaiyulw/seedgoose/blob/master/src/genericSeed.ts#L63 the `get` function returns `undefined` because there somewhere the `domain` key is removed.

`MissingSchemaError: Schema hasn't been registered for model "undefined"`

Given the data:
```json
{
  "Jack": {
    "name": "Jack",
    "articles": [
      {
        "article": "Post",
        "domain": "post"
      }
    ]
  }
}
```

Logging schema on L63 only returns:
```
{
  type: [Function: ObjectId] {
    schemaName: 'ObjectId',
    get: [Function],
    _checkRequired: [Function],
    _cast: [Function: castObjectId],
    cast: [Function: cast],
    checkRequired: [Function]
  },
  refPath: 'domain'
}
```

So `get(root, schema.refPath)` returns undefined because there is no `schema.domain` at that point. I couldn't track down where this is happening though.

**Comment by zhangkaiyulw** [comment]
Hi @hennessyevan, I'm a little bit busy these days. I've setup the new unit test system. I'll continue looking at this issue tomorrow. Thanks for providing these information. If you want to dig into it and fix, feel free to do that. Thanks~ :)
